# Generated by Django 3.1.6 on 2021-05-27 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0002_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParcelRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, null=True)),
                ('last_name', models.CharField(max_length=20, null=True)),
                ('email', models.CharField(max_length=20, null=True)),
                ('mobile', models.CharField(max_length=20, null=True)),
                ('parcel_type', models.CharField(max_length=20, null=True)),
                ('request_date', models.DateField()),
                ('gov_id', models.CharField(max_length=20, null=True)),
                ('gov_no', models.CharField(max_length=20, null=True)),
                ('weight', models.CharField(max_length=20, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('status', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
