# Generated by Django 3.1.6 on 2021-05-27 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0003_parcelrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcelrequest',
            name='email',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='parcelrequest',
            name='first_name',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='parcelrequest',
            name='gov_id',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='parcelrequest',
            name='gov_no',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='parcelrequest',
            name='last_name',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='parcelrequest',
            name='mobile',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='parcelrequest',
            name='parcel_type',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='parcelrequest',
            name='status',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='parcelrequest',
            name='weight',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
