# Generated by Django 3.1.6 on 2021-05-29 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0005_auto_20210527_2243'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receiver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('contact', models.CharField(max_length=50, null=True)),
                ('pin', models.CharField(max_length=50, null=True)),
                ('house', models.CharField(max_length=50, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('state', models.CharField(max_length=50, null=True)),
                ('send_date', models.CharField(max_length=50, null=True)),
                ('parcel_id', models.IntegerField(max_length=50, null=True)),
                ('parcel_status', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
