# Generated by Django 3.1.6 on 2021-05-29 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0006_receiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcelrequest',
            name='parcel_id',
            field=models.IntegerField(max_length=50, null=True),
        ),
    ]
