# Generated by Django 3.1.6 on 2021-05-29 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0007_parcelrequest_parcel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiver',
            name='parcel_date',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='receiver',
            name='parcel_msg',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
